### ISSUE TITLE
Extend Mediawiki Session Length 

### ISSUE THREAD

**Issue by stefan2904** [LosFuzzys/MediaWiki-OAuth2-Github#4]
Currently the session of a user logged in via GitHub expires rather soon. Change this. (Maybe make it a parameter.)

Likely locations:
* https://github.com/LosFuzzys/MediaWiki-OAuth2-Github/blob/master/SpecialOAuth2Github.php#L110
* https://github.com/LosFuzzys/MediaWiki-OAuth2-Github/blob/master/SpecialOAuth2Github.php#L186
* mediawiki config
* php config

**Comment by stefan2904** [comment]
* https://www.mediawiki.org/wiki/Manual:$wgCookieExpiration
* https://www.mediawiki.org/wiki/Manual:$wgExtendedLoginCookieExpiration
* https://www.mediawiki.org/wiki/Manual:$wgObjectCacheSessionExpiry
* http://superuser.com/questions/204905/mediawiki-increase-session-timeout

**Comment by PeterTheOne** [comment]
https://www.mediawiki.org/wiki/Manual:$wgCookieExpiration
and
http://superuser.com/questions/204905/mediawiki-increase-session-timeout
both look good.

**Comment by stefan2904** [comment]
Since `$wgCookieExpiration` is not set in our config I assume it defaults to 30 days which should be ok.

Let's check the php thing ...

Maybe it's also caused by the way the plugin creates the session, see
https://github.com/LosFuzzys/MediaWiki-OAuth2-Github/blob/master/SpecialOAuth2Github.php#L186

**Comment by stefan2904** [comment]
old values for the [mentioned](http://superuser.com/a/204935/373530) properties in our `fpm/php.ini`:

```
; After this number of seconds, stored data will be seen as 'garbage' and
; cleaned up by the garbage collection process.
; http://php.net/session.gc-maxlifetime
; (1440 seconds = 24 minutes)
session.gc_maxlifetime = 1440

; Document expires after n minutes.
; http://php.net/session.cache-expire
session.cache_expire = 180


; Lifetime in seconds of cookie or, if 0, until browser is restarted.
; http://php.net/session.cookie-lifetime
session.cookie_lifetime = 0
```

**Comment by stefan2904** [comment]
Mediawiki currently sets me 3 cookies, the session cookie is set to expire when my browser session ends. This should be ok, but I think this is not what was happening so far.

The other cookies apparently expire after 48 hours.

So cookie expiration != mediawiki session expiration?

**Comment by stefan2904** [comment]
UPDATE:

Setting `$wgCookieExpiration = 30 * 86400;` didn't do the job.

I am now setting `session.gc_maxlifetime = 1440` to 1 day.
(Not sure if this is a good idea. @PeterTheOne, can you check what your servers use for that?)
