### ISSUE TITLE
LogicException: Cannot set a password for a user that is not in the database

### ISSUE THREAD

**Issue by gaieges** [LosFuzzys/MediaWiki-OAuth2-Github#6]
Strange exception I couldn't find a solution for with a little digging, figured I'd bring it up here. 

Having the problem after trying to click the "login via github" link, properly goes through github, comes back to my mediawiki site, and presents the below message.  This is on a fresh install, clean db and `update.php` ran successfully.

MediaWiki `1.28.2 (438c3d6)19:03, 30 April 2017`
PHP `7.1.6-2 (apache2handler)`
MySQL `5.6.36`

OAuth2Github `0.0.2 (a475ffb)19:15, 30 November 2016`

```
[7894c7b69c19cdad4beefe4b] /index.php/Special:OAuth2Github/callback?code=HASH&state=HASH LogicException from line 2511 of /var/www/html/includes/user/User.php: Cannot set a password for a user that is not in the database.

Backtrace:

#0 /var/www/html/includes/user/User.php(2483): User->setPasswordInternal(string)
#1 /var/www/html/extensions/MediaWiki-OAuth2-Github/SpecialOAuth2Github.php(211): User->setPassword(string)
#2 /var/www/html/extensions/MediaWiki-OAuth2-Github/SpecialOAuth2Github.php(110): SpecialOAuth2Github->userHandling(array)
#3 /var/www/html/extensions/MediaWiki-OAuth2-Github/SpecialOAuth2Github.php(36): SpecialOAuth2Github->_callback()
#4 /var/www/html/includes/specialpage/SpecialPage.php(522): SpecialOAuth2Github->execute(string)
#5 /var/www/html/includes/specialpage/SpecialPageFactory.php(577): SpecialPage->run(string)
#6 /var/www/html/includes/MediaWiki.php(283): SpecialPageFactory::executePath(Title, RequestContext)
#7 /var/www/html/includes/MediaWiki.php(851): MediaWiki->performRequest()
#8 /var/www/html/includes/MediaWiki.php(512): MediaWiki->main()
#9 /var/www/html/index.php(43): MediaWiki->run()
#10 {main}
```

**Comment by gaieges** [comment]
I get something similar if I create the user first via self-registration, and then try to login with the account named the same:

```
[6cba3421a568894ffa333a70] /index.php/Special:OAuth2Github/callback?code=45a4d47e87e6bed2c04b&state=595ee7a5f16d32.37332347 MWException from line 205 of /var/www/html/extensions/MediaWiki-OAuth2-Github/SpecialOAuth2Github.php: Unable to create user.

Backtrace:

#0 /var/www/html/extensions/MediaWiki-OAuth2-Github/SpecialOAuth2Github.php(110): SpecialOAuth2Github->userHandling(array)
#1 /var/www/html/extensions/MediaWiki-OAuth2-Github/SpecialOAuth2Github.php(36): SpecialOAuth2Github->_callback()
#2 /var/www/html/includes/specialpage/SpecialPage.php(522): SpecialOAuth2Github->execute(string)
#3 /var/www/html/includes/specialpage/SpecialPageFactory.php(577): SpecialPage->run(string)
#4 /var/www/html/includes/MediaWiki.php(283): SpecialPageFactory::executePath(Title, RequestContext)
#5 /var/www/html/includes/MediaWiki.php(851): MediaWiki->performRequest()
#6 /var/www/html/includes/MediaWiki.php(512): MediaWiki->main()
#7 /var/www/html/index.php(43): MediaWiki->run()
#8 {main}
```

**Comment by stefan2904** [comment]
Thanks for reporting!

I think this is related to [User::setPassword being deprecated since mediawiki 1.27](https://doc.wikimedia.org/mediawiki-core/master/php/classUser.html#a31f8ac46096664222909e4bc5c85519c). 

I'll take a look.

**Comment by stefan2904** [comment]
@gaieges: If you have time, can you test if it works with the fix_password_set branch? Otherwise I'll test it later.

**Comment by gaieges** [comment]
Wow you're quick! Absolutely, can take a look right now.

**Comment by gaieges** [comment]
Works perfectly!  Thanks so much @stefan2904 !

Likely related but not a big deal at all, I also get a warning with the same configuration.  If you want I can create another ticket so we can close this one out.

`Warning: Parameter 1 to OAuth2GithubHooks::onBeforePageDisplay() expected to be a reference, value given in /var/www/html/includes/Hooks.php on line 195`

**Comment by stefan2904** [comment]
Great, thanks!

Yes, please create a new issue for that, makes tracking changes easier. :)

**Comment by gaieges** [comment]
Will do, thanks again @stefan2904 , saved a ton of my time :)
