### ISSUE TITLE
Minor: Parameter 1 to OAuth2GithubHooks::onBeforePageDisplay() expected to be a reference, value given

### ISSUE THREAD

**Issue by gaieges** [LosFuzzys/MediaWiki-OAuth2-Github#8]
By no means a showstopper, just a warning being thrown when using this plugin (regardless of logged in state, just shows it always when warnings are on (ie: `ini_set( 'display_errors', 1 );`).

`Warning: Parameter 1 to OAuth2GithubHooks::onBeforePageDisplay() expected to be a reference, value given in /var/www/html/includes/Hooks.php on line 195`

MediaWiki `1.28.2 (438c3d6)19:03, 30 April 2017`
PHP `7.1.6-2 (apache2handler)`
MySQL `5.7.18`

OAuth2Github `0.0.2 (ebb48c2) 15:05, 7 July 2017`

**Comment by stefan2904** [comment]
I think this is an issue with Mediawiki and PHP 7.1, see [this Mediawiki issue](https://phabricator.wikimedia.org/T153505).

It also says on Mediawiki's [Compatibility page](https://www.mediawiki.org/wiki/Compatibility#PHP):

> The latest stable branch of MediaWiki (1.28) runs on any version of PHP 5.5.9 to PHP 7. Please note that MediaWiki is not yet fully compatible with PHP 7.1, and will emit warnings, but most functionality should work as expected.

**Comment by gaieges** [comment]
I think you're 100% correct.  I just flipped back to 7.0 and the warning seems to have disappeared.  Thanks again!
